 
package clup_owners;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

 
public class trainer_signup extends javax.swing.JFrame {
 
    public trainer_signup() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comb_ex = new javax.swing.JComboBox<>();
        btn_cash = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_name = new javax.swing.JTextField();
        btn_pass = new javax.swing.JPasswordField();
        btn_phnumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comb_time = new javax.swing.JComboBox<>();
        comb_day = new javax.swing.JComboBox<>();
        btn_gmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_rePass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        comb_sport = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_phnumber1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Club Owners");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comb_ex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "less than 1 year", "1 year", "more than 1 year" }));
        getContentPane().add(comb_ex, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 270, 40));
        getContentPane().add(btn_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, 280, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Create Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 160, 30));

        btn_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 260, 40));
        getContentPane().add(btn_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 250, 40));
        getContentPane().add(btn_phnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 260, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cash number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 160, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 110, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sport");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 100, 50));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 180, 50));

        comb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:12", "12:3", "3:6", "6:9" }));
        getContentPane().add(comb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 270, 40));

        comb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));
        getContentPane().add(comb_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 270, 40));
        getContentPane().add(btn_gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 260, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Gmail");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 100, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\3d\\WhatsApp Image 2024-04-18 at 21.40.33_e1b04571.jpg")); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 430, 340));
        getContentPane().add(btn_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Create account admin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 560, 90));
        getContentPane().add(btn_rePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 260, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Re_type Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 180, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("( It must contan @club.com)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Experiance");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 160, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 180, 60));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Time");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, 100, 50));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Day");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 100, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 690, 200, 60));

        comb_sport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "foot ball", "tennis", "swimming" }));
        comb_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_sportActionPerformed(evt);
            }
        });
        getContentPane().add(comb_sport, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 602, 270, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\3d\\WhatsApp Image 2024-04-16 at 03.03.43_f020c253.jpg")); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1920, 1080));
        getContentPane().add(btn_phnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String m="@club.com";
        if (btn_userName.getText().contains(m) &&btn_pass.getText().equals(btn_rePass.getText())&&btn_pass.getText().contains("@") || btn_pass.getText().contains("$") || btn_pass.getText().contains("*") || btn_pass.getText().contains("#") || btn_pass.getText().contains("&")&&!btn_userName.getText().isEmpty() && !btn_pass.getText().isEmpty() && !btn_rePass.getText().isEmpty() && !btn_gmail.getText().isEmpty()&&!btn_name.getText().isEmpty()&&!btn_phnumber.getText().isEmpty()&&!btn_cash.getText().isEmpty()) {

            

        
            trainer a1 = new trainer();
             
             a1.insert_user(btn_name.getText(),btn_phnumber.getText(),btn_gmail.getText(),comb_sport.getSelectedItem().toString(),comb_day.getSelectedItem().toString(),comb_time.getToolTipText(),comb_ex.getSelectedItem().toString(),btn_cash.getText(),btn_userName.getText(), btn_pass.getText());

            JOptionPane.showMessageDialog(this, "Successful");
            this.dispose();

            new home().setVisible(true);

        } else if (btn_cash.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n Cash number not excite");
        else if (btn_pass.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n password not excite");
        else if (btn_rePass.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n re_type password not excite");
        else if (!btn_pass.getText().equals(btn_rePass.getText()))
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n password not same re_type password");

        else if (btn_pass.getText().isEmpty()&& btn_rePass.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n password and re_type password not excite");
        else if(!btn_userName.getText().contains(m))
        JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n user Name must contain @club.com");

        else if (!btn_pass.getText().contains("*") || !btn_pass.getText().contains("#") || !btn_pass.getText().contains("&") || !btn_pass.getText().contains("@") || !btn_pass.getText().contains("$"))
            JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n password not strong" + "\n password must be '#' or '*' or '&' or '@' or '$' ");
        else if (btn_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Can’t Sign Up" +"\n Name not excite");
        } else if (btn_gmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n Gmail not excite" );
        } else if (btn_phnumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n Phone number not excite");
        } else if (btn_cash.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Can’t Sign Up" + "\n Cash number not excite");
        }  



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nameActionPerformed

    private void comb_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_sportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_sportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trainer_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trainer_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trainer_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trainer_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trainer_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btn_cash;
    private javax.swing.JTextField btn_gmail;
    private javax.swing.JTextField btn_name;
    private javax.swing.JPasswordField btn_pass;
    private javax.swing.JTextField btn_phnumber;
    private javax.swing.JTextField btn_phnumber1;
    private javax.swing.JPasswordField btn_rePass;
    private javax.swing.JTextField btn_userName;
    private javax.swing.JComboBox<String> comb_day;
    private javax.swing.JComboBox<String> comb_ex;
    private javax.swing.JComboBox<String> comb_sport;
    private javax.swing.JComboBox<String> comb_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
